"""add_notifications_table

Revision ID: a004c1a3a508
Revises: d7a821909c42
Create Date: 2025-09-26 15:32:32.647883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a004c1a3a508'
down_revision: Union[str, None] = 'd7a821909c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fcm_tokens_id', table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_user_favorite_clubs_id', table_name='user_favorite_clubs')
    op.drop_table('user_favorite_clubs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_clubs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='user_favorite_clubs_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorite_clubs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_favorite_clubs_pkey')
    )
    op.create_index('ix_user_favorite_clubs_id', 'user_favorite_clubs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invited_player_id'], ['users.id'], name='invitations_invited_player_id_fkey'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name='invitations_inviter_id_fkey'),
    sa.ForeignKeyConstraint(['turn_id'], ['pregame_turns.id'], name='invitations_turn_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fcm_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fcm_tokens_pkey'),
    sa.UniqueConstraint('token', name='fcm_tokens_token_key')
    )
    op.create_index('ix_fcm_tokens_id', 'fcm_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
