"""Update Court model with description and correct field names

Revision ID: d0085e1b85cd
Revises: c2a8103db612
Create Date: 2025-09-22 16:11:29.326955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0085e1b85cd'
down_revision: Union[str, None] = 'c2a8103db612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('turn_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('match_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'turns', ['turn_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'matches', ['match_id'], ['id'])
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    op.add_column('matches', sa.Column('score', sa.String(), nullable=True))
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('AVAILABLE', 'RESERVED', 'IN_PROGRESS', 'COMPLETED', name='matchstatus'),
               existing_nullable=True)
    op.add_column('turns', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('turns', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('turns', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('turns', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('AVAILABLE', 'BOOKED', 'CANCELLED', 'COMPLETED', name='turnstatus'),
               existing_nullable=True)
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.drop_constraint('turns_user_id_fkey', 'turns', type_='foreignkey')
    op.drop_column('turns', 'user_id')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('turns', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('turns_user_id_fkey', 'turns', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.alter_column('turns', 'status',
               existing_type=sa.Enum('AVAILABLE', 'BOOKED', 'CANCELLED', 'COMPLETED', name='turnstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('turns', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('turns', 'updated_at')
    op.drop_column('turns', 'price')
    op.alter_column('matches', 'status',
               existing_type=sa.Enum('AVAILABLE', 'RESERVED', 'IN_PROGRESS', 'COMPLETED', name='matchstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('matches', 'score')
    op.add_column('bookings', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('bookings', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'match_id')
    op.drop_column('bookings', 'turn_id')
    # ### end Alembic commands ###
