"""add_category_field_to_users

Revision ID: d7a821909c42
Revises: d7aaf67ab82d
Create Date: 2025-09-25 14:12:21.577647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a821909c42'
down_revision: Union[str, None] = 'd7aaf67ab82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fcm_tokens_id', table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.drop_table('invitations')
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invited_player_id'], ['users.id'], name='invitations_invited_player_id_fkey'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name='invitations_inviter_id_fkey'),
    sa.ForeignKeyConstraint(['turn_id'], ['pregame_turns.id'], name='invitations_turn_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fcm_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fcm_tokens_pkey'),
    sa.UniqueConstraint('token', name='fcm_tokens_token_key')
    )
    op.create_index('ix_fcm_tokens_id', 'fcm_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
