"""add_fcm_tokens_table

Revision ID: d7aaf67ab82d
Revises: 25787086b0a0
Create Date: 2025-09-24 13:33:52.284986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7aaf67ab82d'
down_revision: Union[str, None] = '25787086b0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_clubs')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.alter_column('clubs', 'opening_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.alter_column('clubs', 'closing_time',
               existing_type=postgresql.TIME(),
               nullable=False,
               existing_server_default=sa.text("'22:00:00'::time without time zone"))
    op.add_column('matches', sa.Column('score', sa.String(), nullable=True))
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('AVAILABLE', 'RESERVED', 'IN_PROGRESS', 'COMPLETED', name='matchstatus'),
               existing_nullable=True)
    op.drop_column('pregame_turns', 'player_side')
    op.drop_column('pregame_turns', 'player_court_position')
    op.alter_column('turns', 'turns_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.alter_column('turns', 'turns_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('pregame_turns', sa.Column('player_court_position', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('pregame_turns', sa.Column('player_side', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('matches', 'status',
               existing_type=sa.Enum('AVAILABLE', 'RESERVED', 'IN_PROGRESS', 'COMPLETED', name='matchstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('matches', 'score')
    op.alter_column('clubs', 'closing_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'22:00:00'::time without time zone"))
    op.alter_column('clubs', 'opening_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_server_default=sa.text("'08:00:00'::time without time zone"))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.alter_column('bookings', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('user_favorite_clubs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='user_favorite_clubs_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorite_clubs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_favorite_clubs_pkey'),
    sa.UniqueConstraint('user_id', 'club_id', name='user_favorite_clubs_user_id_club_id_key')
    )
    # ### end Alembic commands ###
